### ISSUE TITLE
More than 20 connections are opened for postgres

### ISSUE THREAD

**Issue by asaf** [crossid/accessbot#186]
SqlAlchemy default connection pool is 5, we should check where do we create engines and if we re-use them correctly.

[accessbot_postgres_too_many_connections.txt](https://github.com/user-attachments/files/16630383/accessbot_postgres_too_many_connections.txt)

**Comment by ErezSha** [comment]
@asaf I don't know what causes it, but it looks like an issue with Azure rather than our code.

I sent 120 concurrent requests to neon, and it works fine.
As you can see, the number of connections never went over 12.

![Image](https://github.com/user-attachments/assets/22688b45-7549-4b6a-8005-762c13148e03)


In any case, I'll make a PR to use the current engine, I just don't think it's actually the issue.
