### ISSUE TITLE
Archive conversation

### ISSUE THREAD

**Issue by asaf** [crossid/accessbot#61]
The purpose of this feature is to _hide_ conversations from the user and boost performance.
Since this is a security product we should never actually delete conversations.

## Questions

- Should archived or move it archive collection?
- Do we need another API to query archived conversations?
- How to unarchive?
- A REST endpoint to archive a conversation (PATCH vs .archive)

**Comment by ErezSha** [comment]
1. If we want to boost performance, we should also archive checkpoints and messages when archiving conversations.
2. There are 2 options:
2.1 _Separate tables_ - this can cause consistency issues, because if we're not careful, ids might change and conversation -> msgs -> checkpoints can get out of syc
2.2  _Table Partitioning_ - Postgres allows for partitioning by column values, so in theory we could keep all data in the same tables, partition by status and never change the rows ids and FKs
3. I wonder what the actual use case for this will be, as we'll want to show archived conversations to the user in the UI so they can unarchive it, so we'll query archived conversations anyway.
3.1 Moreover, most of our queries for conversation table is on the PK (except for list), which means it's already very efficient.

**Comment by asaf** [comment]
@ErezSha what is done within the attached PR?

**Comment by ErezSha** [comment]
@asaf I created a search index on the conversation status and added an archive + unarchive routes
